name: Publish to npm

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Authenticate to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc

      - name: Install dependencies
        run: |
          echo "Checking for bun.lockb..."
          if [ -f bun.lockb ]; then
            echo "bun lockfile found, running bun install"
            bun install --frozen-lockfile
          else
            echo "no bun lockfile found, running bun install"
            bun install
          fi

      - name: Build
        run: bun run build

      - name: Run tests
        run: bun test || true

      - name: Sync package.json version with tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          # remove leading v if present
          VERSION=${TAG#v}
          echo "Setting package.json version to $VERSION"
          node -e "let p=require('./package.json'); p.version='$VERSION'; require('fs').writeFileSync('package.json', JSON.stringify(p,null,2));"

      - name: Smoke test compiled artifact
        run: |
          node -e "require('./dist/index.js'); console.log('smoke test ok');"

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public
